"""Add image column to table Animals

Revision ID: 080f0b8a2044
Revises: e6d7a8391e2e
Create Date: 2024-11-20 19:44:49.858230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080f0b8a2044'
down_revision = 'e6d7a8391e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animals', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
